# Generated by Django 4.0.3 on 2022-04-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=150)),
                ('size', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
