# Generated by Django 4.0.3 on 2022-04-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='sq',
        ),
    ]
