# Generated by Django 4.0.3 on 2022-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('Việt Nam', 'Việt Nam'), ('United States', 'United States'), ('Russia', 'Russia')], default='vietNam', max_length=50),
        ),
    ]
