# Generated by Django 4.0.3 on 2022-05-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='statitic',
            field=models.FloatField(default=0),
        ),
    ]
